#!/bin/sh
mydir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ushrrfs="$(dirname "$mydir")"
basedir="$(dirname "$ushrrfs")"
agentdir="$basedir/fix/.agent"
source $ushrrfs/fix_rrfs_locations.sh
mkdir -p $basedir/fix

filetype=$(file $agentdir)
if [[ ! "$filetype" == *"symbolic link"* ]]; then
  rm -rf $agentdir
fi
ln -snf $FIX_RRFS_LOCATION $agentdir
