#!/bin/bash

date
export PS4='+ $SECONDS + '
#
#-----------------------------------------------------------------------
#
# Source the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${HOMErrfs}/ush/source_util_funcs.sh

#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that generates lateral boundary 
condition (LBC) files (in NetCDF format) for all LBC update hours (except 
hour zero). 
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set the NCO standard environment variables (Table 1, pp.4)
#
#-----------------------------------------------------------------------
#
# Flag for shared working directory
flag_shared_working_dir="FALSE"

# Define job and jobid by default for rocoto
WORKFLOW_MANAGER="${WORKFLOW_MANAGER:-rocoto}"
if [ "${WORKFLOW_MANAGER}" = "rocoto" ]; then
  if [ "${SCHED}" = "slurm" ]; then
    job_default=${SLURM_JOB_NAME}
    pid_default=${SLURM_JOB_ID}
  elif [ "${SCHED}" = "pbspro" ]; then
    job_default=${PBS_JOBNAME}
    pid_default=${PBS_JOBID}
  else
    job_default="task"
    pid_default=$$
  fi
  if [ "${flag_shared_working_dir}" = "TRUE" ]; then
    jobid_default="${job_default}.${PDY}${cyc}"
  else
    jobid_default="${job_default}.${PDY}${cyc}.${pid_default}"
  fi
fi
export job="${job:-${job_default}}"
export jobid="${jobid:-${jobid_default}}"

# Set environment variables
export NET="${NET:-${NET_default}}"
export RUN="${RUN:-${RUN_default}}"

export USHrrfs="${HOMErrfs}/ush"
export EXECrrfs="${HOMErrfs}/exec"
export PARMrrfs="${HOMErrfs}/parm"
export SCRIPTSrrfs="${HOMErrfs}/scripts"
export LOGDIR="${COMROOT}/output/logs"
#
#-----------------------------------------------------------------------
#
# Create a temp working directory (DATA) and cd into it.
#
#-----------------------------------------------------------------------
#
export DATA="${DATA:-${DATAROOT}/${jobid}}"
mkdir -p $DATA
cd $DATA
#
#-----------------------------------------------------------------------
#
# Set other environment variables.
#
#-----------------------------------------------------------------------
#
export bcgrp="${bcgrp:-0}"
export bcgrpnum="${bcgrpnum:-0}"
#
#-----------------------------------------------------------------------
#
# Set COM type definitions.
#
#-----------------------------------------------------------------------
#
[[ "$WORKFLOW_MANAGER" = "rocoto" ]] && export COMROOT=$COMROOT
export COMIN="${COMIN:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc})}"
export COMOUT="${COMOUT:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc})}"
export COMOUT_lbcs="${COMOUT}${SLASH_ENSMEM_SUBDIR}/lbcs"

mkdir -p ${COMOUT}
mkdir -p ${COMOUT_lbcs}

# Run setpdy to initialize PDYm and PDYp variables
export cycle="${cycle:-t${cyc}z}"
setpdy.sh
. ./PDY
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job.
#
#-----------------------------------------------------------------------
#
export pgmout="${DATA}/OUTPUT.$$"
env

$SCRIPTSrrfs/exrrfs_make_lbcs.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#-----------------------------------------------------------------------
#
# Whether or not working directory DATA should be kept.
#
#-----------------------------------------------------------------------
#
if [ "${KEEPDATA}" = "NO" ] && [ "${flag_shared_working_dir}" = "FALSE" ]; then
  rm -rf ${DATA}
fi
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

