#!/bin/bash

#-----------------------------------------------------------------------
#
# This J-JOB script runs the standalone No-Var Cloud Analysis
#
#-----------------------------------------------------------------------
#
date
export PS4='+ $SECONDS + '
#
#-----------------------------------------------------------------------
#
# Source the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${HOMErrfs}/ush/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a standalone No-Var cloud
analysis with FV3 for the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set the NCO standard environment variables (Table 1, pp.4)
#
#-----------------------------------------------------------------------
#
# Flag for shared working directory
flag_shared_working_dir="FALSE"

# Define job and jobid by default for rocoto
WORKFLOW_MANAGER="${WORKFLOW_MANAGER:-rocoto}"
if [ "${WORKFLOW_MANAGER}" = "rocoto" ]; then
  if [ "${SCHED}" = "slurm" ]; then
    job=${SLURM_JOB_NAME}
    pid=${SLURM_JOB_ID}
  elif [ "${SCHED}" = "pbspro" ]; then
    job=${PBS_JOBNAME}
    pid=${PBS_JOBID}
  else
    job="task"
    pid=$$
  fi
  if [ "${flag_shared_working_dir}" = "TRUE" ]; then
    jobid="${job}.${PDY}${cyc}"
  else
    jobid="${job}.${PDY}${cyc}.${pid}"
  fi
fi

# Set environment variables: job card (or rocoto xml)
export envir="${envir:-para}"
export model_ver="${model_ver:-v0.0.0}"
export KEEPDATA="${KEEPDATA:-YES}"
export SENDCOM="${SENDCOM:-YES}"

# Set environment variables: j-job
export NET="${NET:-rrfs}"
export RUN="${RUN:-rrfs}"
export USHrrfs="${HOMErrfs}/ush"
export EXECrrfs="${HOMErrfs}/exec"
export PARMrrfs="${HOMErrfs}/parm"
export SCRIPTSrrfs="${HOMErrfs}/scripts"
export LOGDIR="${COMROOT}/output/logs"
#
#-----------------------------------------------------------------------
#
# Create a temp working directory (DATA) and cd into it.
#
#-----------------------------------------------------------------------
#
export DATA="${DATA:-${DATAROOT}/${jobid}}"
mkdir -p $DATA
cd $DATA
#
#-----------------------------------------------------------------------
#
# Set other environment variables.
#
#-----------------------------------------------------------------------
#
# CYCLE_TYPE is to indicate which type of cycle this job for:
#   spinup: this job is for spin-up cycles
#   others(prod): this job is for product cycle
#
export CYCLE_TYPE="${CYCLE_TYPE:-prod}"
export CYCLE_SUBTYPE="${CYCLE_SUBTYPE:-empty}"
export MEM_TYPE="${MEM_TYPE:-empty}"

export CDATE="${CDATE:-${PDY}${cyc}}"
#
#-----------------------------------------------------------------------
#
# Set COM type definitions.
#
#-----------------------------------------------------------------------
#
[[ "$WORKFLOW_MANAGER" = "rocoto" ]] && export COMROOT=$COMROOT
if [ "${MACHINE}" = "WCOSS2" ]; then
  export COMIN="${COMIN:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc}${SLASH_ENSMEM_SUBDIR})}"
  export COMOUT_BASEDIR="${COMOUT_BASEDIR:-$(compath.py -o ${NET}/${model_ver})}"
else
  export COMIN="${COMIN:-${COMROOT}/${NET}/${model_ver}/${RUN}.${PDY}/${cyc}${SLASH_ENSMEM_SUBDIR}}"
  export COMOUT_BASEDIR="${COMOUT_BASEDIR:-${COMROOT}/${NET}/${model_ver}}"
fi

if [ "${MEM_TYPE}" = "MEAN" ]; then
  export COMOUT="${COMOUT_BASEDIR}/${RUN}.${PDY}/${cyc}/ensmean"
else
  export COMOUT="${COMOUT_BASEDIR}/${RUN}.${PDY}/${cyc}${SLASH_ENSMEM_SUBDIR}"
fi
export COMOUT_gridspec="${COMOUT_BASEDIR}/grid_spec"

mkdir -p ${COMOUT}
mkdir -p ${COMOUT_gridspec}

# Run setpdy to initialize PDYm and PDYp variables
export cycle="${cycle:-t${cyc}z}"
setpdy.sh
. ./PDY
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job.
#
#-----------------------------------------------------------------------
#
export pgmout="${DATA}/OUTPUT.$$"
env

$SCRIPTSrrfs/exrrfs_nonvarcldanl.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#-----------------------------------------------------------------------
#
# Whether or not working directory DATA should be kept.
#
#-----------------------------------------------------------------------
#
if [ "${KEEPDATA}" = "NO" ] && [ "${flag_shared_working_dir}" = "FALSE" ]; then
  rm -rf ${DATA}
fi
date
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

